import type { Metadata } from "next";
import "./globals.css";
import Providers from "./Providers";

export const metadata: Metadata = {
  title: "SaleorDemo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body
        className={
          "font-work-sans text bg-default-white dark:bg-dark-bg text-black dark:text-white"
        }
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
